lo_program = statement+;

statement = assignment | comment;

assignment = "def", IDENTIFIER, expression;

expression = expression_head, expression_body | expression_body | variable;

expression_head = "(", variable*, ")";

expression_body = "{", expression+, "}";

variable = IDENTIFIER;



60ml ÖL